CREATE TABLE IF NOT EXISTS roles (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS companies (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(80) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	role_id INT NOT NULL,
	company_id INT NOT NULL,
	company_name VARCHAR(80) NOT NULL,
	name VARCHAR(80) NOT NULL,
	birthdate VARCHAR(15) NOT NULL,
	email VARCHAR(300) NOT NULL,
	enabled BOOLEAN NOT NULL,
	password VARCHAR(80) NOT NULL,
	address VARCHAR(300) NOT NULL,
	phone_number VARCHAR(80) NOT NULL,
	emergency_contact VARCHAR(80) NOT NULL,
	relationship VARCHAR(15) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (role_id) REFERENCES roles (id),
	FOREIGN KEY (company_id) REFERENCES companies (id)
);